
name: Lamine_push

on : [push]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pre-commit
        # For example, using `pytest`
        run:  uv run pre-commit run -a


      - name: Run unittest
        # For example, using `pytest`
        run:  uv run python -m unittest

strategy:
  matrix:
    python-version:
      - "3.10"
      - "3.11"
      - "3.12"
